export const FETCH_DIGITAL_CANVAS_DATA_REQUEST = 'FETCH_DIGITAL_CANVAS_DATA_REQUEST';
export const FETCH_DIGITAL_CANVAS_DATA_SUCCESS = 'FETCH_DIGITAL_CANVAS_DATA_SUCCESS';
export const FETCH_DIGITAL_CANVAS_DATA_FAILED = 'FETCH_DIGITAL_CANVAS_DATA_FAILED';
