export const FORGOT_USER_REQUEST = 'FORGOT_USER_REQUEST';
export const FORGOT_USER_SUCCESS = 'FORGOT_USER_SUCCESS';
export const FORGOT_USER_FAILURE = 'FORGOT_USER_FAILURE';
export const RESET_USER_REQUEST = 'RESET_USER_REQUEST';
export const RESET_USER_SUCCESS = 'RESET_USER_SUCCESS';
export const RESET_USER_FAILURE = 'RESET_USER_FAILURE';
