export const PLAY_ON_DEVICE_REQUEST = 'PLAY_ON_DEVICE_REQUEST';
export const PLAY_ON_DEVICE_SUCCESS = 'PLAY_ON_DEVICE_SUCCESS';
export const PLAY_ON_DEVICE_FAILURE = 'PLAY_ON_DEVICE_FAILURE';

export const OPEN_DEVICE_MENU = 'OPEN_DEVICE_MENU';
export const CLOSE_DEVICE_MENU = 'CLOSE_DEVICE_MENU';
export const TOGGLE_DEVICE_MENU = 'TOGGLE_DEVICE_MENU';
