export const ADD_YOURNFT_FILE = 'ADD_YOURNFT_FILE';

export const START_YOURNFT_UPLOAD = 'START_YOURNFT_UPLOAD';
export const CREATE_YOURNFT_UPLOAD = 'CREATE_YOURNFT_UPLOAD';
export const COMPLETE_YOURNFT_UPLOAD = 'COMPLETE_YOURNFT_UPLOAD';
export const FINALIZE_YOURNFT_UPLOAD = 'FINALIZE_YOURNFT_UPLOAD';

export const YOURNFT_UPLOAD_FAILURE = 'YOURNFT_UPLOAD_FAILURE';
export const YOURNFT_UPLOAD_PROGRESS = 'YOURNFT_UPLOAD_PROGRESS';
export const YOURNFT_UPLOAD_CANCEL = 'YOURNFT_UPLOAD_CANCEL';
export const YOURNFT_UPLOAD_ABORTED = 'YOURNFT_UPLOAD_ABORTED';
export const SET_YOURNFT_ASPECT_RATIO = 'SET_YOURNFT_ASPECT_RATIO';
